apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
- namespace.yml
- mongodb-pvc.yml
- mongodb-deployment.yml
- mongodb-service.yml
- todo-api-deployment.yml
- todo-api-service.yml
- prometheus-deployment.yml
- prometheus-service.yml
- grafana-deployment.yml
- grafana-service.yml

images:
- name: osza/todo-api
  newTag: latest

labels:
- pairs:
    app: todo-stack
    managed-by: argocd