apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

images:
- name: osza/todo-api
  newTag: a5a80aab18c9a906917b406f62c5cb2531ab9cc5

commonLabels:
  app: todo-api
  managed-by: argocd