apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

images:
- name: osza/todo-api
  newTag: latest

commonLabels:
  app: todo-api
  managed-by: argocd